#include "stdafx.h"

std:: string NationAnthem[] = {"Unbreakable Union of freeborn Republics",
"Great Russia has welded forever to stand.",
"Created in struggle by will of the people,",
"United and mighty, our Soviet land!",
"Sing to the Motherland, home of the free,",
"Bulwark of peoples in brotherhood strong.",
"O Party of Lenin, the strength of the people,",
"To Communism's triumph lead us on!",
"Through tempests the sunrays of freedom have cheered us,",
"Along the new path where great Lenin did lead.",
"To a righteous cause he raised up the peoples,",
"Inspired them to labour and valourous deed.",
"In the victory of Communism's deathless ideal,",
"We see the future of our dear land.",
"And to her fluttering scarlet banner",
"Selflessly true we always shall stand!" };

std::string BohemianRhaphosdy[] = { "Is this the real life ?",
"Is this just fantasy ?",
"Caught in a landslide,",
"No escape from reality.",
"",
"Open your eyes,",
"Look up to the skies and see,",
"I'm just a poor boy, I need no sympathy,",
"Because I'm easy come, easy go,",
"Little high, little low,",
"Any way the wind blows doesn't really matter to me, to me.",
"",
"Mama, just killed a man,",
"Put a gun against his head,",
"Pulled my trigger, now he's dead.",
"Mama, life had just begun,",
"But now I've gone and thrown it all away.",
"",
"Mama, ooh,",
"Didn't mean to make you cry,",
"If I'm not back again this time tomorrow,",
"Carry on, carry on as if nothing really matters.",
"",
"Too late, my time has come,",
"Sends shivers down my spine,",
"Body's aching all the time.",
"Goodbye, everybody, I've got to go,",
"Gotta leave you all behind and face the truth.",
"",
"Mama, ooh(any way the wind blows),",
"I don't wanna die,",
"I sometimes wish I'd never been born at all.",
"",
"I see a little silhouetto of a man,",
"Scaramouche, Scaramouche, will you do the Fandango ?",
"Thunderbolt and lightning,",
"Very, very frightening me.",
"(Galileo)Galileo.",
"(Galileo)Galileo,",
"Galileo Figaro",
"Magnifico - o - o - o - o.",
"",
"I'm just a poor boy, nobody loves me.",
"He's just a poor boy from a poor family,",
"Spare him his life from this monstrosity.",
"",
"Easy come, easy go, will you let me go ?",
"Bismillah!No, we will not let you go. (Let him go!)",
"Bismillah!We will not let you go. (Let him go!)",
"Bismillah!We will not let you go. (Let me go!)",
"Will not let you go. (Let me go!)",
"Never let you go(Never, never, never, never let me go)",
"Oh oh oh oh",
"No, no, no, no, no, no, no",
"Oh, mama mia, mama mia(Mama mia, let me go.)",
"Beelzebub has a devil put aside for me, for me, for me.",
"",
"So you think you can stone me and spit in my eye ?",
"So you think you can love me and leave me to die ?",
"Oh, baby, can't do this to me, baby,",
"Just gotta get out, just gotta get right outta here.",
"",
"(Ooooh, ooh yeah, ooh yeah)",
"",
"Nothing really matters,",
"Anyone can see,",
"Nothing really matters,",
"Nothing really matters to me.",
"",
"Any way the wind blows."
};